### ISSUE TITLE
Error after updating typescript to 2.4

### ISSUE THREAD

**Issue by bmarotta** [electricessence/TypeScript.NET#64]
After updating typescript to version 2.4 I get the following error while building. I'm using the umd version.

```
(...)/node_modules/typescript-dotnet-umd/System.Linq/Enumerable.d.ts(212,18): error TS2430: Interface 'NotEmptyEnumerable<T>' incorrectly extends interface 'ILinqEnumerable<T>'.
  Types of property 'aggregate' are incompatible.
    Type '(func: (previous: T, current: T) => T, seed?: T) => T' is not assignable to type '{ (func: (previous: T, current: T, index: number) => T, seed: T): T; (func: (previous: T, current...'.
      Types of parameters 'func' and 'func' are incompatible.
```

**Comment by electricessence** [comment]
Working on this.

**Comment by electricessence** [comment]
A lot of upgrades to the lib.d.ts file in 2.4

**Comment by electricessence** [comment]
Ok, I've made an update but left the min version as 2.3.2.  It should be working now.
If not, you should go back to 2.3.2 because 2.4 is currently having stack overflow issues:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
https://github.com/Microsoft/TypeScript/issues/17097

**Comment by bmarotta** [comment]
Ok thanks. When do you have the stack overflow? ON my build it is not 
happening. But I'm just using some classes

**Comment by electricessence** [comment]
It doesn't happen to everyone.  Just certain build situations.  TS .NET has a complex build.

**Comment by electricessence** [comment]
Did the new npm package solve your problem?

**Comment by bmarotta** [comment]
Yes

**Comment by electricessence** [comment]
GREAT!

**Comment by bmarotta** [comment]
Thanks for the fast support!

**Comment by electricessence** [comment]
Dude, thank you for letting me know!
